### ISSUE TITLE
Accept an optional platform spec in the environments.yaml

### ISSUE THREAD

**Issue by leeleavitt** [nh13/conda-env-builder#30]
I have found `platform` specifications to be a useful feature in `conda-lock`, as it provides an option for locking dependencies per environment specified. It would be great if `conda-env-builder` could also include this option.

Currently, `conda-env-builder` does not support platform specifications in the `environment.yaml` file. This requires developers to manually add platform specifications, which can be a time-consuming process and could potentially lead to errors.

I understand that adding new features can be a complex process, but I wanted to request that this feature be considered for future development. Thank you for your work on this tool.

**Comment by nh13** [comment]
Are you looking for full support for conda-lock (see #21) or are you looking for a [`platforms`](https://github.com/conda/conda-lock#platform-specification) section on the same level as `channels` and `dependencies`?

**Comment by nh13** [comment]
@leeleavitt see #31 . Can you give it a shot?

**Comment by leeleavitt** [comment]
Hi Nils,

Just wanted to follow up on my previous message [here](https://github.com/conda-incubator/conda-env-builder/pull/31#issuecomment-1450735456). It turns out that the feature requires one more change to work properly. My apologies for approving the pull request before thoroughly testing it on my end.

Best regards, Lee

**Comment by nh13** [comment]
@leeleavitt no worries, can you take a look here: #34?  Note that the Assemble and Solve commands will not actually use `platforms` (e.g. solve using `conda-lock`, see #21), but will pass through as-is.

**Comment by leeleavitt** [comment]
Thanks again for this rapid feature development.
